pub(super) type DEV_HANDLE = *mut libc::c_void;

newtype_enum! {
    pub enum DEVICE_INFO_CMD {
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_ID = 0,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_VENDOR = 1,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_MODEL = 2,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_TLTYPE = 3,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_DISPLAYNAME = 4,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_ACCESS_STATUS = 5,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_USER_DEFINED_NAME = 6,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_SERIAL_NUMBER = 7,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_VERSION = 8,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_TIMESTAMP_FREQUENCY = 9,
        DEVICE_INFO_CMD_LIST_DEVICE_INFO_CUSTOM_ID = 1000,
    }
}

newtype_enum! {
    pub enum DEVICE_ACCESS_FLAGS {
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_UNKNOWN = 0,
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_NONE = 1,
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_READONLY = 2,
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_CONTROL = 3,
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_EXCLUSIVE = 4,
        DEVICE_ACCESS_FLAGS_LIST_DEVICE_ACCESS_CUSTOM_ID = 1000,
    }
}
